pipeline {
    agent any

    stages {
        stage('Environment Check') {
            steps {
                sh 'node --version'
                sh 'npm --version'
                sh 'this-command-does-not-exist'
            }
        }
    }
}
